Console.BackgroundColor = ConsoleColor.DarkRed;
Console.ForegroundColor = ConsoleColor.White;
Console.WriteLine("Você também tem que eu sei");
Console.WriteLine("Aquela pessoa, não adianta negar");
Console.WriteLine("Que tem passe livre carta branca na sua vida para ir e voltar");
Console.WriteLine("Quando quiser, nunca vai deixar de ser o que é, é é");
Console.WriteLine("Todo mundo tem uma pessoa, aquela pessoa");
Console.WriteLine("Que te faz esquecer todas as outras");
Console.WriteLine("Todo mundo tem uma pessoa, aquela pessoa");
Console.WriteLine("Não precisa dia e nem hora pra chegar");
Console.WriteLine("Na portaria do meu coração já tem seu nome");
Console.WriteLine("Pode entrar");
Console.WriteLine("Você também tem que eu sei");
Console.WriteLine("Aquela pessoa, não adianta, nega não");
Console.WriteLine("Que tem passe livre carta branca na sua vida para ir e voltar");
Console.WriteLine("Quando quiser, nunca vai deixar de ser o que é, é é");
Console.WriteLine("Todo mundo tem uma pessoa, aquela pessoa");
Console.WriteLine("Que te faz esquecer todas as outras");
Console.WriteLine("Todo mundo tem uma pessoa, aquela pessoa");
Console.WriteLine("Não precisa dia e nem hora pra chegar");
Console.WriteLine("Na portaria do meu coração já tem seu nome");
Console.WriteLine("Todo mundo tem uma pessoa, aquela pessoa");
Console.WriteLine("Que te faz esquecer todas as outras");
Console.WriteLine("Todo mundo tem uma pessoa, aquela pessoa");
Console.WriteLine("Não precisa dia e nem hora pra chegar");
Console.WriteLine("Na portaria do meu coração já tem seu nome");
Console.WriteLine("Pode entrar");